spring:
  application:
    name: tale
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}:3306/tale?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    hikari:
      idle-timeout: 300000
      max-lifetime: 1800000
    properties:
      hibernate:
        format_sql: true
    show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
    output:
      ansi.enabled: always
    servlet:
      multipart:
        max-file-size: 1GB
        max-request-size: 1GB
  data:
    redis:
      port: 6379
      host: ${REDIS_URL}
logging:
  level:
    org.springframework.data.redis.cache: DEBUG
cloud:
  aws:
    s3:
      bucket: tosibucket
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
service:
  user:
    url: ${USER_URL}
springdoc:
  api-docs:
    path: /docs/tales
  swagger-ui:
    urls:
      - name: 동화
        url: https://www.tosi.world/docs/tales
      - name: 회원
        url: https://www.tosi.world/docs/users/v3/api-docs
      - name: 커스텀 동화
        url: https://www.tosi.world/docs/custom-tales/v3/api-docs
      - name: 채팅
        url: https://www.tosi.world/docs/chat/v3/api-docs
