apiVersion: v1
kind: Service
metadata:
  name: tosi-tale-svc
spec:
  selector:
    app: tosi-tale
    tier: backend
  ports:
    - port: 80 # 80으로 연결하면 http 기본 포트이기 때문에 포트 명시 필요없음
      targetPort: 8080
  type: ClusterIP # ingress가 외부 명령을 받아서 전달
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tosi-tale-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tosi-tale
      tier: backend
  template:
    metadata:
      labels:
        app: tosi-tale
        tier: backend
    spec:
      containers:
        - name: tosi-be-tale
          image: dyckerkim/tosi-be-tale:latest # 재시작하면 최신 이미지 pull
          envFrom:
            - secretRef: # mysql, s3 인증
                name: tosi-tale-scrt
          env:
            - name: MYSQL_URL
              value: tosi-db-tale-svc.default
            - name: REDIS_URL
              value: tosi-cc-svc.default
            - name: USER_URL
              value: http://tosi-user-svc.default/api/users
