apiVersion: v1
kind: Service
metadata:
  name: tosi-tale-svc
  namespace: prod-tosi
spec:
  selector:
    app: tosi-tale
    tier: backend
  ports:
    - port: 80 # 80으로 연결하면 http 기본 포트이기 때문에 포트 명시 필요없음
      targetPort: 8080
  type: ClusterIP # ingress가 외부 명령을 받아서 전달
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tosi-tale-dep
  namespace: prod-tosi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tosi-tale
      tier: backend
  template:
    metadata:
      labels:
        app: tosi-tale
        tier: backend
    spec:
      serviceAccountName: prod-tosi-sa
      containers:
        - name: tosi-be-tale
          # 이미지 주소 CD 파이프라인에서 치환
          image: dummy
          # 컨테이너 살아있는지 확인
          livenessProbe:
            httpGet:
              path: /actuator/tales/health/liveness
              port: 8080
            initialDelaySeconds: 30 # 30초 후 검사 시작
            periodSeconds: 10 # 10초마다 검사
            timeoutSeconds: 2 # 2초 안에 응답 없으면 실패로 간주
            failureThreshold: 3 # 연속 3회 실패 시 재시작
          # 컨테이너가 트래픽을 받을 준비가 되었는지 확인
          readinessProbe:
            httpGet:
              path: /actuator/tales/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          # 볼륨을 컨테이너의 파일 경로로 연결
          volumeMounts:
            - name: tale-credentials-vol
              mountPath: /mnt/secrets-store
              readOnly: true
          # 볼륨 기반으로 쿠버네티스 Secret 리소스 생성
          envFrom:
            - secretRef:
                name: tale-credentials
      # 볼륨 생성
      # CSI 드라이버에서 SecretProviderClass를 참조하여 AWS API를 호출
      volumes:
        - name: tale-credentials-vol
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: tale-credentials
