name: TALE CD

# release로 시작하는 브랜치에 push될 때
on:
  push:
    branches: ["develop"]

# 깃헙 토큰 권한 생성
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 액션 시작
      - name: Checkout code
        uses: actions/checkout@v4

      # 도커 이미지 생성(buildx 방식이 빠름)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # tale 폴더에 있는 Docker 이미지 빌드 및 푸시
      # 커밋 번호를 태그로 지정
      - name: Build and Push Docker Image
        run: |
          IMAGE=${{ secrets.DOCKER_REPO }}/tosi-be-tale
          docker buildx build --push -t $IMAGE:${{ github.sha }} tale

      # deployment 이미지 주소 변경하여 태그 기록 남기기
      # tale.yml 파일에서 image: 줄을 찾아서 치환
      - name: Update image in manifest
        run: |
          IMAGE=${{ secrets.DOCKER_REPO }}/tosi-be-tale:${{ github.sha }}
          sed -i "s|image:.*|image: $IMAGE|" kubernetes/tale.yml

      # aws 인증
      # aws에 github actions용 role 생성 후 eks access에 추가
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActions2EKS

      # kubectl을 TOSI 클러스터와 연결
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ap-northeast-2 --name tosiCluster

      # 변경된 이미지 주소를 반영할 수 있도록 apply 실행
      - name: Deploy
        run: kubectl apply -f=kubernetes/tale.yml

      # 60초 동안 배포 상태 체크 (성공 - successfully rolled out 메시지)
      - name: Check deployment status
        run: |
          kubectl rollout status deployment/tosi-tale-dep -n prod-tosi --timeout=60s
